# Generated by Django 4.2.1 on 2023-06-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_postmodel_date_alter_postmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='media',
            field=models.FileField(null=True, upload_to='post/media/'),
        ),
    ]
