# Generated by Django 4.2.1 on 2023-06-05 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
        ('userprofile', '0004_remove_userprofilemodel_user_backgroud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='user_followers',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='user_following',
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='user_posts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.postmodel'),
        ),
    ]
