# Generated by Django 4.2.1 on 2023-06-05 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_remove_userprofilemodel_user_followers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='user_avatar',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='user_description',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='user_status',
        ),
    ]
